name: Generate Docs

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Generate TypeDoc
        run: npm run docs

      - name: Checkout docs-repo
        uses: actions/checkout@v3
        with:
          repository: rage-js/docs
          token: ${{ secrets.GITHUB_TOKEN }}
          path: rage-js-docs

      - name: Copy docs to rage-js-docs
        run: |
          rm -rf rage-js-docs/docs
          cp -R docs rage-js-docs/

      - name: Commit and push changes to rage-js-docs
        run: |
          cd rage-js-docs
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add docs
          git commit -m "Update docs"
          git push
